# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: everyday.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='everyday.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x65veryday.proto\"n\n\x06OneDay\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12 \n\x07\x63ontent\x18\x02 \x03(\x0b\x32\x0f.OneDay.Content\x1a\x34\n\x07\x43ontent\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x03(\t\"#\n\x08\x45veryDay\x12\x17\n\x06oneday\x18\x01 \x03(\x0b\x32\x07.OneDayb\x06proto3'
)




_ONEDAY_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='OneDay.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='OneDay.Content.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='OneDay.Content.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='OneDay.Content.image', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=128,
)

_ONEDAY = _descriptor.Descriptor(
  name='OneDay',
  full_name='OneDay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='OneDay.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='OneDay.content', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ONEDAY_CONTENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=128,
)


_EVERYDAY = _descriptor.Descriptor(
  name='EveryDay',
  full_name='EveryDay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oneday', full_name='EveryDay.oneday', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=165,
)

_ONEDAY_CONTENT.containing_type = _ONEDAY
_ONEDAY.fields_by_name['content'].message_type = _ONEDAY_CONTENT
_EVERYDAY.fields_by_name['oneday'].message_type = _ONEDAY
DESCRIPTOR.message_types_by_name['OneDay'] = _ONEDAY
DESCRIPTOR.message_types_by_name['EveryDay'] = _EVERYDAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OneDay = _reflection.GeneratedProtocolMessageType('OneDay', (_message.Message,), {

  'Content' : _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
    'DESCRIPTOR' : _ONEDAY_CONTENT,
    '__module__' : 'everyday_pb2'
    # @@protoc_insertion_point(class_scope:OneDay.Content)
    })
  ,
  'DESCRIPTOR' : _ONEDAY,
  '__module__' : 'everyday_pb2'
  # @@protoc_insertion_point(class_scope:OneDay)
  })
_sym_db.RegisterMessage(OneDay)
_sym_db.RegisterMessage(OneDay.Content)

EveryDay = _reflection.GeneratedProtocolMessageType('EveryDay', (_message.Message,), {
  'DESCRIPTOR' : _EVERYDAY,
  '__module__' : 'everyday_pb2'
  # @@protoc_insertion_point(class_scope:EveryDay)
  })
_sym_db.RegisterMessage(EveryDay)


# @@protoc_insertion_point(module_scope)
